#! /bin/bash
######################################################################################################################################## Coversa inicial com user: vamos começar dando boas vinda, e fazer as seguintes perguntas: atualizar o sistema, instalar pacotes, re-## mover pacotes, ver insformaçãoes de pacotes, limpar o sistema e sair. 							            ########################################################################################################################################

contador_do_while=1

echo "Oi, o quê deseja: "

echo

#Nessas perguntas o que o usuario deseja: atualizar, remover, instalar, ver informações e limpar o sistema#

echo "digite 's' para sim e 'n' para não"

echo

while [ "$contador_do_while" = 1 ] : 
do
	echo "Atualizar o sistema? s/n"
	read atualizar_o_sistema
	
	echo
	
	echo "Instalar pacotes? s/n"
	read instalar_pacotes
	
	echo
	
	echo "remover pacotes? s/n"
	read remover_pacotes
	
	echo
	
	echo "ver informações de pacotes? s/n"
	read informacoes_de_pacotes
	
	echo
	
	echo "Limpar o sistema? s/n"
	read limpar_o_sistema

	echo "Deseja refazer as perguntas? s/n"
	read repetir_as_perguntas

	#pergunta para o usuario se quer repetir as perguntas e coloca o valor das váriavel para nada#
	
	if test "$repetir_as_perguntas" = "s"
	then
		echo "As perguntas vão aparecer novamente"
		atualizar_o_sistema=''
		instalar_pacotes=''
		remover_pacotes=''
		informacoes_de_pacotes=''
		limpar_o_sistema=''
		repetir_as_perguntas=''	
	else
		lista_de_afazeres={$atualizar_o_sistema, $instalar_pacotes,\
		       	$remover_pacotes, $informacoes_do_pacotes, \ 
			$limpar_o_sistema, $repetir_as_perguntas}
		break	
	fi
done
echo "$lisa_de_afazeres"

